# Generated by Django 5.1.7 on 2025-05-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_trapeciohistorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trapeciohistorial',
            options={'verbose_name': 'Historial de cálculo de trapecio', 'verbose_name_plural': 'Historial de cálculos de trapecio'},
        ),
        migrations.RenameField(
            model_name='trapeciohistorial',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='trapeciohistorial',
            name='subintervalos',
            field=models.IntegerField(default=1),
        ),
    ]
